### ISSUE TITLE
Error: Cannot find module 'mime' 

### ISSUE THREAD

**Issue by dustMason** [unconed/TermKit#18]
```
18 May 11:04:33 - Client 021951160626485944 connected
worker:  

worker:  node.js:134

worker:          throw e; // process.nextTick error, or 'error' event on first tick

worker:          ^

worker:  Error: Cannot find module 'mime'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/Users/turtle/Documents/CodeLibrary/TermKit/Node/shell/meta.js:1:74)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.<anonymous> (/Users/turtle/Documents/CodeLibrary/TermKit/Node/shell/formatter.js:2:12)
```

I followed the install instructions on the readme and arrived at this error when trying to launch TermKit.app. Using node 0.4.7 (installed at /usr/local/bin/node) and npm 1.0.6.

**Comment by tomhartley** [comment]
How did you manage to resolve this issue? I installed mime using npm, and got this:

<pre>npm it worked if it ends with ok
npm cli [ 'install', 'mime' ]
npm version 0.1.25
npm config file /Users/Tom/.npmrc
npm config file /usr/local/Cellar/node/0.1.104/etc/npmrc
npm install pkg mime
npm fetch data mime
npm GET mime
npm install pkg mime
npm install pkg mime@1.2.2
npm buildAll About to unpack
npm unpack [ 'mime', '1.2.2' ]
npm exec tar "xzf" "/usr/local/lib/node/.npm/.cache/mime/1.2.2/package.tgz" "--strip-components=1" "-C" "/usr/local/lib/node/.npm/mime/1.2.2/package"
npm createMain mime
npm linkLib mime-1.2.2
npm ! WARNING !  
npm ! WARNING ! Symlinking the lib directory is deprecated
npm ! WARNING ! Please don't rely on this feature, as it will be removed.
npm ! WARNING ! Use the 'main' module instead.
npm ! WARNING !  
npm activate mime@1.2.2
npm update-dependents only version, no dependencies to update
npm build Success: mime@1.2.2
npm ok</pre>


I then went ahead, started node, and when I connected I got this:

<pre>worker:  node.js:289

worker:          throw new Error("Cannot find module '" + request + "'");

worker:                ^

worker:  Error: Cannot find module 'mime'
    at loadModule (node.js:289:15)
    at require (node.js:420:14)
    at Object.<anonymous> (/Users/Tom/Documents/OSS/TermKit/Node/shell/meta.js:1:74)
    at Module._compile (node.js:472:25)
    at Module._loadScriptSync (node.js:482:10)
    at Module.loadSync (node.js:352:12)
    at loadModule (node.js:297:14)
    at require (node.js:420:14)
    at Object.<anonymous> (/Users/Tom/Documents/OSS/TermKit/Node/shell/formatter.js:2:12)
    at Module._compile (node.js:472:25)</pre>

**Comment by dustMason** [comment]
i had to create a symlink for my node modules. something like this:
`ln -s /usr/lib/node ~/.node_modules`

also make sure that you have the module installed: `npm install mime`

**Comment by tomhartley** [comment]
Sorry for wasting your time, the problem was that I still had a ridiculously old version of node.js installed by default or something... Works like a charm now :)
