### ISSUE TITLE
Cannot find module 'mime'

### ISSUE THREAD

**Issue by sanity** [unconed/TermKit#24]
I followed the installation instructions, but when I run the app I get the following error:

18 May 17:07:24 - Initializing client with transport "websocket"
18 May 17:07:24 - Client 5248795922379941 connected
worker:  

worker:  node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^

worker:  Error: Cannot find module 'mime'
    at Function._resolveFilename (module.js:299:11)
    at Function._load (module.js:245:25)
    at require (module.js:327:19)
    at Object.<anonymous> (/private/tmp/TermKit/Node/shell/meta.js:1:74)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)
    at Function._load (module.js:276:12)
    at require (module.js:327:19)
    at Object.<anonymous> (/private/tmp/TermKit/Node/shell/formatter.js:2:12)

18 May 17:07:28 - Client 5248795922379941 disconnected

**Comment by ghost** [comment]
Same thing happening to me

19 May 00:20:07 - socket.io ready - accepting connections
19 May 00:20:15 - Initializing client with transport "websocket"
19 May 00:20:15 - Client 5208459862042218 connected
worker:  

worker:  node.js:183
        throw e; // process.nextTick error, or 'error' event on first tick
        ^

worker:  Error: Cannot find module 'mime'
    at Function._resolveFilename (module.js:322:11)
    at Function._load (module.js:267:25)
    at require (module.js:367:19)
    at Object.<anonymous> (/Developer/TermKit/Node/shell/meta.js:1:74)
    at Module._compile (module.js:423:26)
    at Object..js (module.js:429:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at require (module.js:367:19)
    at Object.<anonymous> (/Developer/TermKit/Node/shell/formatter.js:2:12)

**Comment by kennethreitz** [comment]
Same here. You have to set the `NODE_PATH` environment var to the location of your node binary.

**Comment by mikbe** [comment]
Setting NODE_PATH doesn't work for me. I tried setting it to the exact path to the bin and the directory to the bin; neither worked. I also installed mime with npm to make sure it was there.

```
18 May 20:59:57 - socket.io ready - accepting connections
18 May 21:00:01 - Initializing client with transport "websocket"
18 May 21:00:01 - Client 9138696517329663 connected
worker:  

worker:  node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^

worker:  Error: Cannot find module 'mime'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/Users/supersecret/development/external/TermKit/Node/shell/meta.js:1:74)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.<anonymous> (/Users/supersecret/development/external/TermKit/Node/shell/formatter.js:2:12)
```

**Comment by francisl** [comment]
Did you installed mime ?

``` bash
curl http://npmjs.org/install.sh | sh
```

**Comment by mikbe** [comment]
@francisl
Yes, "I also installed mime with npm to make sure it was there."

The problem was I had a really old version of npm installed, 0.3.18. Installing the latest version of npm fixed the problem. Thanks for your help!

**Comment by andycasey** [comment]
I had this issue too.

I just made a symbolic link from where the mime module was termkit/node_modules/mime to termkit/Node with:

cd termkit/Node
ln -s ../../node_modules/mime mime

**Comment by sanity** [comment]
I'm closing this because I solved the problem by upgrading to the latest version of npm - which I would have done if I had followed the installation instructions to the letter.

Might be worth mentioning to ensure you have the latest version though.

**Comment by ghost** [comment]
sanity: I did follow the instructions to the letter. I was installing npm and mime for the first time, both with the latest versions. This is still an issue

**Comment by DarrellBrogdon** [comment]
I can confirm furrylemmings' comment. That said, andycasey's fix worked.

**Comment by danishkhan** [comment]
Updating worked for me as well
