### ISSUE TITLE
On Startup or anytime .write is called

### ISSUE THREAD

**Issue by evan108108** [unconed/TermKit#35]
worker:  TypeError: Cannot read property 'write' of undefined
at Object.<anonymous> (/xxx/TermKit/Node/shell/reader.js:12:23)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at Object.<anonymous> (/xxx/TermKit/Node/shell/formatter.js:10:14)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)

**Comment by kindjar** [comment]
You probably have an old version of node.js (like I did). If you installed via brew, you may need to do a `brew update` and then reinstall node. That fixed the above error for me.
