### ISSUE TITLE
Failed to load resource: cancelled ... localhost:2222/socket.io/xhr-polling//

### ISSUE THREAD

**Issue by eobanb** [unconed/TermKit#38]
I launch TermKit and a plain black screen appears.  In the WebKit console, the following error appears about every 10 seconds:

```
Failed to load resource: cancelled ... localhost:2222/socket.io/xhr-polling//1305822806506
```

With new numbers on the end each time.

socket.io seems to be installed correctly though:

```
$ npm install socket.io
npm info it worked if it ends with ok
npm info using npm@0.3.18
npm info using node@v0.4.7
npm info preinstall socket.io@0.6.18
npm info install socket.io@0.6.18
npm info postinstall socket.io@0.6.18
npm info predeactivate socket.io@0.6.18
npm info deactivate socket.io@0.6.18
npm info postdeactivate socket.io@0.6.18
npm info preactivate socket.io@0.6.18
npm info activate socket.io@0.6.18
npm info postactivate socket.io@0.6.18
npm info build Success: socket.io@0.6.18
npm ok
```

Any thoughts?

**Comment by hmottestad** [comment]
did you clone correctly? Have you tried updating node?

From readme file:
5. Clone the TermKit repository: git clone git@github.com:unconed/TermKit.git --recursive
6. Users of older git versions will need to type: git submodule update --init

**Comment by Aveesek** [comment]
After running all the command in terminal from http://www.techdrivein.com/2011/06/termkit-is-terminal-reimagined-install.html , at last I got this. After hours of installation work comes the biggest disappointment. 

abhisek@abhisek1 ~/TermKitProj/TermKit $ node Node/nodekit.js
module.js:394
    throw new Error('require.paths is removed. Use ' +
          ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.Object.defineProperty.get (module.js:394:11)
    at Object.<anonymous> (/home/abhisek/TermKitProj/TermKit/Node/nodekit.js:5:8)
    at Module._compile (module.js:462:26)
    at Object.Module._extensions..js (module.js:480:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:503:10)
    at startup (node.js:132:16)
    at node.js:817:3
