### ISSUE TITLE
Error when trying to run the Node daemon, nodekit.js

### ISSUE THREAD

**Issue by nesv** [unconed/TermKit#73]
The following error gets raised when I attempt to run the `nodekit.js` file:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:378:11)
    at Object.<anonymous> (/Users/nsaika/Downloads/TermKit/Node/nodekit.js:6:8)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

Running `echo $NODE_PATH` gives me the following output:

```
/usr/local/lib/node_modules
```

For what it is worth, I following the installation instructions in the main README.

**Comment by matths** [comment]
I think this is perhaps due to the new version (v0.6.13) of node that come out lately?
They changed some of the core module names, namely sys -> util.

I have that error, too. Any workarounds, yet?

**Comment by yankcrime** [comment]
This is easily fixed by commenting out / removing the following line from nodekit.js:
<code>
require.paths.unshift(__dirname + '/../Shared/');
</code>

And then adding TermKit/Shared folder to your NODE_PATH environment variable.

**Comment by matths** [comment]
thanks for that. That worked so far. The daemon runs.
I am on OSX and when I unzip and start the TermKit.app its runs, but keeps black all the time (which might be a duplicate to #70). No prompt at all. :(
Pressing ⌥⌘C to access the WebKit console works though.

**Comment by nesv** [comment]
Commenting/removing that line in `Node/nodekit.js` gets me past that initial error. Here's a new error I'm getting:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'protocol'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/nsaika/Downloads/TermKit/Node/router.js:3:16)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
```

**Comment by yankcrime** [comment]
@indienick Did you add the Termkit/Shared directory to your NODE_PATH environment variable?

**Comment by nesv** [comment]
That worked. Thank you very much. :)

**Comment by SunDi3yansyah** [comment]
ERROR?

how to solve this problem
![error](https://lh5.googleusercontent.com/-7YbJ8YQkiSE/VHWZeGW68TI/AAAAAAAAARY/WMO5AkMnwOw/s800/Screenshot+from+2014-11-26+16:07:26.pngK)

when I gave comments
![error](https://lh4.googleusercontent.com/-RMBeU483E_w/VHWZ2KKc1cI/AAAAAAAAAR4/ILRaP7jpXZY/s800/Screenshot+from+2014-11-26+16:13:26.png)

I'am using ubuntu 14.04
