### ISSUE TITLE
require.paths is removed. Use node_modules folders...

### ISSUE THREAD

**Issue by alexsilva** [unconed/TermKit#78]
Install mode:

```
~/tmp$ git clone https://github.com/Floby/TermKit.git --recursive
  Cloning into 'TermKit'...
  remote: Counting objects: 2605, done.
  remote: Compressing objects: 100% (1127/1127), done.
  remote: Total 2605 (delta 1310), reused 2605 (delta 1310)
  Receiving objects: 100% (2605/2605), 17.17 MiB | 299.00 KiB/s, done.
  Resolving deltas: 100% (1310/1310), done.
  Checking connectivity... done.
  No submodule mapping found in .gitmodules for path 'Node/socket.io-node'

~/tmp/TermKit$ npm install
  npm http GET https://registry.npmjs.org/connect
  npm http GET https://registry.npmjs.org/socket.io
  npm http GET https://registry.npmjs.org/mime
  npm http 200 https://registry.npmjs.org/mime
  npm http 200 https://registry.npmjs.org/socket.io
  npm http GET https://registry.npmjs.org/socket.io/-/socket.io-0.6.18.tgz
  npm http 200 https://registry.npmjs.org/socket.io/-/socket.io-0.6.18.tgz
  npm http 200 https://registry.npmjs.org/connect
  npm http GET https://registry.npmjs.org/connect/-/connect-1.2.3.tgz
  npm http 200 https://registry.npmjs.org/connect/-/connect-1.2.3.tgz
  npm WARN engine connect@1.2.3: wanted: {"node":">= 0.4.1 < 0.5.0"} (current:      {"node":"v0.10.20","npm":"1.3.11"})
  npm http GET https://registry.npmjs.org/qs
  npm http 200 https://registry.npmjs.org/qs
  npm http GET https://registry.npmjs.org/qs/-/qs-0.6.6.tgz
  npm http 200 https://registry.npmjs.org/qs/-/qs-0.6.6.tgz
  mime@1.2.11 node_modules/mime  
  socket.io@0.6.18 node_modules/socket.io
  connect@1.2.3 node_modules/connect
  └── qs@0.6.6
```

Error:

```
~/tmp/TermKit$ node Node/nodekit.js
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.Object.defineProperty.get (module.js:388:11)
    at Object.<anonymous> (/home/alex/tmp/TermKit/Node/nodekit.js:5:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

Deps install:

```
~/tmp/TermKit$ npm install router
~/tmp/TermKit$ npm install connect
~/tmp/TermKit$ npm install config
```

Config:

```
export NODE_PATH="/~/tmp/TermKit/node_modules"
```

Edit(nodekit.js):

```
#!/usr/bin/env node
var termkit = {
  version: 1,
};
//require.paths.unshift(__dirname); <<< Here
//require.paths.unshift(__dirname+'/../Shared'); <<< Here

// Load requirements.
var http = require('http'),  
    io = require('socket.io')
    router = require("router"),
    connect = require('connect');

// Load config file.
var config = require('config').getConfigSources(); <<< Here

// Set up http server.
var server = connect.createServer(
    connect.static(__dirname+'/../HTML')
)

server.listen(2222, function() {
    console.log('server listening at http://localhost:2222');
});

// Set up WebSocket and handlers.
var socket = io.listen(server); 
socket.on('connection', function (client) {
  var p = new router(client); <<< Here
});
```

New errors:

```
~/tmp/TermKit$ node Node/nodekit.js
WARNING: No configurations found in configuration directory:
WARNING: /home/alex/tmp/TermKit/config
WARNING: See https://www.npmjs.org/package/config for more information.
WARNING: config.getConfigSources() is deprecated.  Use config.util.getConfigSources() instead.
WARNING: See https://github.com/lorenwest/node-config/wiki/Future-Compatibility#upcoming-incompatibilities
31 Jul 15:14:23 - socket.io ready - accepting connections
server listening at http://localhost:2222

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at Function.Flashsocket.init (/home/alex/tmp/TermKit/node_modules/socket.io/lib/socket.io/transports/flashsocket.js:44:17)
    at /~/tmp/TermKit/node_modules/socket.io/lib/socket.io/listener.js:49:54
    at Array.forEach (native)
    at new module.exports (/~//tmp/TermKit/node_modules/socket.io/lib/socket.io/listener.js:46:27)
    at Object.exports.listen (/~/tmp/TermKit/node_modules/socket.io/lib/socket.io/index.js:11:10)
    at Object.<anonymous> (/~/TermKit/Node/nodekit.js:27:17)
```

After:

```
/~/tmp/TermKit$ sudo node Node/nodekit.js
```

Result in black screen on browser!

```
~/tmp/TermKit$ sudo node Node/nodekit.js
WARNING: No configurations found in configuration directory:
WARNING: /home/alex/tmp/TermKit/config
WARNING: See https://www.npmjs.org/package/config for more information.
WARNING: config.getConfigSources() is deprecated.  Use config.util.getConfigSources() instead.
WARNING: See https://github.com/lorenwest/node-config/wiki/Future-Compatibility#upcoming-incompatibilities
31 Jul 15:25:07 - socket.io ready - accepting connections
server listening at http://localhost:2222
31 Jul 15:25:20 - Initializing client with transport "xhr-polling"
31 Jul 15:25:20 - Client 9281128391157836 connected
31 Jul 15:25:21 - Initializing client with transport "xhr-polling"
```

**Comment by johan** [comment]
@alexsilva I believe making a pull request with these changes in it would make them happen sooner:
- clone the repo
- check out a new branch from master
- make the changes
- commit them
- push to your repo clone
- create pull request from the branch

(if you are new to using git and github)
