### ISSUE TITLE
node nodekit.js is giving errors

### ISSUE THREAD

**Issue by telnasser** [unconed/TermKit#9]
Executing  "node nodekit.js" is giving the following error:

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:290:11)
    at Function._load (module.js:242:25)
    at require (module.js:318:19)
    at Object.<anonymous> (/Users/telnasser/Downloads/unconed-TermKit-1544e7e/Node/nodekit.js:12:10)
    at Module._compile (module.js:374:26)
    at Object..js (module.js:380:10)
    at Module.load (module.js:306:31)
    at Function._load (module.js:272:10)
    at Array.<anonymous> (module.js:393:10)
    at EventEmitter._tickCallback (node.js:108:26)

Can someone help please?

**Comment by barrettj** [comment]
I'm experiencing this issue as well.  It looks like the files are all there.

**Comment by barrettj** [comment]
Found a work around, did a npm -install socket.io

**Comment by telnasser** [comment]
I did this, but still:

Tamer-El-Nassers-MacBook-Pro:Node telnasser$ sudo npm install socket.io
npm info it worked if it ends with ok
npm info using npm@0.3.12
npm info using node@v0.4.1
npm info preinstall socket.io@0.6.18
npm info install socket.io@0.6.18
npm info postinstall socket.io@0.6.18
npm info predeactivate socket.io@0.6.18
npm info deactivate socket.io@0.6.18
npm info postdeactivate socket.io@0.6.18
npm info preactivate socket.io@0.6.18
npm info activate socket.io@0.6.18
npm info postactivate socket.io@0.6.18
npm info build Success: socket.io@0.6.18
npm ok
Tamer-El-Nassers-MacBook-Pro:Node telnasser$ node nodekit.js 

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'socket.io'
    at Function._resolveFilename (module.js:290:11)
    at Function._load (module.js:242:25)
    at require (module.js:318:19)
    at Object.<anonymous> (/Users/telnasser/Downloads/unconed-TermKit-1544e7e/Node/nodekit.js:12:10)
    at Module._compile (module.js:374:26)
    at Object..js (module.js:380:10)
    at Module.load (module.js:306:31)
    at Function._load (module.js:272:10)
    at Array.<anonymous> (module.js:393:10)
    at EventEmitter._tickCallback (node.js:108:26)

**Comment by ghost** [comment]
I had the same issue. Try turning off your firewall in system preferences.

**Comment by telnasser** [comment]
I'm using snow leopard ...

**Comment by Floby** [comment]
your npm version is outdated.
check ou npm 1.0 and run `npm install socket.io` in the root directory.
also my [pull reuest](https://github.com/unconed/TermKit/pull/6) fix this issue by removing the socket.io submodule from the repo and managing modules with npm entirely

**Comment by Shifty0x88** [comment]
it could also be that you did not use the --recursive switch on your git command

Use the command:

<pre><code>git clone https://github.com/unconed/TermKit.git <strong>--recursive</strong></code></pre>


this is because inside his repository there is a reference to another repository created by someone else

**Comment by telnasser** [comment]
I've removed everything and did 

<code>git clone https://github.com/unconed/TermKit.git --recursive</code>

It worked at last!!

Thanks everyone for your support.
